server:
  port: 8888
mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.jtboot.manager.pojo
logging:
  level:
    com.jtboot.manager.mapper: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: zhenxin
    password: 123456
    url: jdbc:mysql:///jtdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

localPath: D:/zhenxin/java/jt/upload/

urlPath: http://image.jt.com/